base_url = "https://ethan-clip.vercel.app"
[book]
title = "Ethan's Clip"
description = "Ethan's Clip"
src = "content"
language = "zh"
authors = ["Ethan Chen"]

[output.html]
git-repository-url = "https://github.com/ethanjtch/clip"
edit-url-template = "https://github.com/ethanjtch/clip/edit/main/{path}"

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "ethan.jt.chen@outlook.com"
from_name = "Ethan"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = "ethan.jt.chen@outlook.com"
